# Generated by Django 4.2.5 on 2023-12-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=32)),
                ("short_name", models.CharField(max_length=16)),
                ("unit_type", models.CharField(max_length=32)),
            ],
        ),
    ]
