name: CI for Testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Make envfile
        run: |
          touch .env
      - name: Run test
        run: ./run selfcheck
      - name: Upload coverage results to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: /app/coverage/coverage.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

